// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.networks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GroupPoliciesContentFilteringAllowedUrlPatternsArgs extends com.pulumi.resources.ResourceArgs {

    public static final GroupPoliciesContentFilteringAllowedUrlPatternsArgs Empty = new GroupPoliciesContentFilteringAllowedUrlPatternsArgs();

    /**
     * A list of URL patterns that are allowed
     * 
     */
    @Import(name="patterns")
    private @Nullable Output<List<String>> patterns;

    /**
     * @return A list of URL patterns that are allowed
     * 
     */
    public Optional<Output<List<String>>> patterns() {
        return Optional.ofNullable(this.patterns);
    }

    /**
     * How URL patterns are applied. Can be &#39;network default&#39;, &#39;append&#39; or &#39;override&#39;.
     * 
     */
    @Import(name="settings")
    private @Nullable Output<String> settings;

    /**
     * @return How URL patterns are applied. Can be &#39;network default&#39;, &#39;append&#39; or &#39;override&#39;.
     * 
     */
    public Optional<Output<String>> settings() {
        return Optional.ofNullable(this.settings);
    }

    private GroupPoliciesContentFilteringAllowedUrlPatternsArgs() {}

    private GroupPoliciesContentFilteringAllowedUrlPatternsArgs(GroupPoliciesContentFilteringAllowedUrlPatternsArgs $) {
        this.patterns = $.patterns;
        this.settings = $.settings;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GroupPoliciesContentFilteringAllowedUrlPatternsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GroupPoliciesContentFilteringAllowedUrlPatternsArgs $;

        public Builder() {
            $ = new GroupPoliciesContentFilteringAllowedUrlPatternsArgs();
        }

        public Builder(GroupPoliciesContentFilteringAllowedUrlPatternsArgs defaults) {
            $ = new GroupPoliciesContentFilteringAllowedUrlPatternsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param patterns A list of URL patterns that are allowed
         * 
         * @return builder
         * 
         */
        public Builder patterns(@Nullable Output<List<String>> patterns) {
            $.patterns = patterns;
            return this;
        }

        /**
         * @param patterns A list of URL patterns that are allowed
         * 
         * @return builder
         * 
         */
        public Builder patterns(List<String> patterns) {
            return patterns(Output.of(patterns));
        }

        /**
         * @param patterns A list of URL patterns that are allowed
         * 
         * @return builder
         * 
         */
        public Builder patterns(String... patterns) {
            return patterns(List.of(patterns));
        }

        /**
         * @param settings How URL patterns are applied. Can be &#39;network default&#39;, &#39;append&#39; or &#39;override&#39;.
         * 
         * @return builder
         * 
         */
        public Builder settings(@Nullable Output<String> settings) {
            $.settings = settings;
            return this;
        }

        /**
         * @param settings How URL patterns are applied. Can be &#39;network default&#39;, &#39;append&#39; or &#39;override&#39;.
         * 
         * @return builder
         * 
         */
        public Builder settings(String settings) {
            return settings(Output.of(settings));
        }

        public GroupPoliciesContentFilteringAllowedUrlPatternsArgs build() {
            return $;
        }
    }

}
