// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.networks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SnmpUserArgs extends com.pulumi.resources.ResourceArgs {

    public static final SnmpUserArgs Empty = new SnmpUserArgs();

    /**
     * The passphrase for the SNMP user.
     * 
     */
    @Import(name="passphrase")
    private @Nullable Output<String> passphrase;

    /**
     * @return The passphrase for the SNMP user.
     * 
     */
    public Optional<Output<String>> passphrase() {
        return Optional.ofNullable(this.passphrase);
    }

    /**
     * The username for the SNMP user.
     * 
     */
    @Import(name="username")
    private @Nullable Output<String> username;

    /**
     * @return The username for the SNMP user.
     * 
     */
    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private SnmpUserArgs() {}

    private SnmpUserArgs(SnmpUserArgs $) {
        this.passphrase = $.passphrase;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SnmpUserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SnmpUserArgs $;

        public Builder() {
            $ = new SnmpUserArgs();
        }

        public Builder(SnmpUserArgs defaults) {
            $ = new SnmpUserArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param passphrase The passphrase for the SNMP user.
         * 
         * @return builder
         * 
         */
        public Builder passphrase(@Nullable Output<String> passphrase) {
            $.passphrase = passphrase;
            return this;
        }

        /**
         * @param passphrase The passphrase for the SNMP user.
         * 
         * @return builder
         * 
         */
        public Builder passphrase(String passphrase) {
            return passphrase(Output.of(passphrase));
        }

        /**
         * @param username The username for the SNMP user.
         * 
         * @return builder
         * 
         */
        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The username for the SNMP user.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public SnmpUserArgs build() {
            return $;
        }
    }

}
