// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.networks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SwitchAlternateManagementInterfaceSwitchArgs extends com.pulumi.resources.ResourceArgs {

    public static final SwitchAlternateManagementInterfaceSwitchArgs Empty = new SwitchAlternateManagementInterfaceSwitchArgs();

    /**
     * Switch alternative management IP. To remove a prior IP setting, provide an empty string
     * 
     */
    @Import(name="alternateManagementIp")
    private @Nullable Output<String> alternateManagementIp;

    /**
     * @return Switch alternative management IP. To remove a prior IP setting, provide an empty string
     * 
     */
    public Optional<Output<String>> alternateManagementIp() {
        return Optional.ofNullable(this.alternateManagementIp);
    }

    /**
     * Switch gateway must be in IP format. Only and must be specified for Polaris switches
     * 
     */
    @Import(name="gateway")
    private @Nullable Output<String> gateway;

    /**
     * @return Switch gateway must be in IP format. Only and must be specified for Polaris switches
     * 
     */
    public Optional<Output<String>> gateway() {
        return Optional.ofNullable(this.gateway);
    }

    /**
     * Switch serial number
     * 
     */
    @Import(name="serial")
    private @Nullable Output<String> serial;

    /**
     * @return Switch serial number
     * 
     */
    public Optional<Output<String>> serial() {
        return Optional.ofNullable(this.serial);
    }

    /**
     * Switch subnet mask must be in IP format. Only and must be specified for Polaris switches
     * 
     */
    @Import(name="subnetMask")
    private @Nullable Output<String> subnetMask;

    /**
     * @return Switch subnet mask must be in IP format. Only and must be specified for Polaris switches
     * 
     */
    public Optional<Output<String>> subnetMask() {
        return Optional.ofNullable(this.subnetMask);
    }

    private SwitchAlternateManagementInterfaceSwitchArgs() {}

    private SwitchAlternateManagementInterfaceSwitchArgs(SwitchAlternateManagementInterfaceSwitchArgs $) {
        this.alternateManagementIp = $.alternateManagementIp;
        this.gateway = $.gateway;
        this.serial = $.serial;
        this.subnetMask = $.subnetMask;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SwitchAlternateManagementInterfaceSwitchArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SwitchAlternateManagementInterfaceSwitchArgs $;

        public Builder() {
            $ = new SwitchAlternateManagementInterfaceSwitchArgs();
        }

        public Builder(SwitchAlternateManagementInterfaceSwitchArgs defaults) {
            $ = new SwitchAlternateManagementInterfaceSwitchArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param alternateManagementIp Switch alternative management IP. To remove a prior IP setting, provide an empty string
         * 
         * @return builder
         * 
         */
        public Builder alternateManagementIp(@Nullable Output<String> alternateManagementIp) {
            $.alternateManagementIp = alternateManagementIp;
            return this;
        }

        /**
         * @param alternateManagementIp Switch alternative management IP. To remove a prior IP setting, provide an empty string
         * 
         * @return builder
         * 
         */
        public Builder alternateManagementIp(String alternateManagementIp) {
            return alternateManagementIp(Output.of(alternateManagementIp));
        }

        /**
         * @param gateway Switch gateway must be in IP format. Only and must be specified for Polaris switches
         * 
         * @return builder
         * 
         */
        public Builder gateway(@Nullable Output<String> gateway) {
            $.gateway = gateway;
            return this;
        }

        /**
         * @param gateway Switch gateway must be in IP format. Only and must be specified for Polaris switches
         * 
         * @return builder
         * 
         */
        public Builder gateway(String gateway) {
            return gateway(Output.of(gateway));
        }

        /**
         * @param serial Switch serial number
         * 
         * @return builder
         * 
         */
        public Builder serial(@Nullable Output<String> serial) {
            $.serial = serial;
            return this;
        }

        /**
         * @param serial Switch serial number
         * 
         * @return builder
         * 
         */
        public Builder serial(String serial) {
            return serial(Output.of(serial));
        }

        /**
         * @param subnetMask Switch subnet mask must be in IP format. Only and must be specified for Polaris switches
         * 
         * @return builder
         * 
         */
        public Builder subnetMask(@Nullable Output<String> subnetMask) {
            $.subnetMask = subnetMask;
            return this;
        }

        /**
         * @param subnetMask Switch subnet mask must be in IP format. Only and must be specified for Polaris switches
         * 
         * @return builder
         * 
         */
        public Builder subnetMask(String subnetMask) {
            return subnetMask(Output.of(subnetMask));
        }

        public SwitchAlternateManagementInterfaceSwitchArgs build() {
            return $;
        }
    }

}
