// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.administered;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.meraki.Utilities;
import com.pulumi.meraki.administered.LicensingSubscriptionSubscriptionsClaimArgs;
import com.pulumi.meraki.administered.inputs.LicensingSubscriptionSubscriptionsClaimState;
import com.pulumi.meraki.administered.outputs.LicensingSubscriptionSubscriptionsClaimItem;
import com.pulumi.meraki.administered.outputs.LicensingSubscriptionSubscriptionsClaimParameters;
import java.lang.Boolean;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ~&gt;Warning: This resource does not represent a real-world entity in Meraki Dashboard, therefore changing or deleting this resource on its own has no immediate effect. Instead, it is a task part of a Meraki Dashboard workflow. It is executed in Meraki without any additional verification. It does not check if it was executed before or if a similar configuration or action
 * already existed previously.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="meraki:administered/licensingSubscriptionSubscriptionsClaim:LicensingSubscriptionSubscriptionsClaim")
public class LicensingSubscriptionSubscriptionsClaim extends com.pulumi.resources.CustomResource {
    @Export(name="item", refs={LicensingSubscriptionSubscriptionsClaimItem.class}, tree="[0]")
    private Output<LicensingSubscriptionSubscriptionsClaimItem> item;

    public Output<LicensingSubscriptionSubscriptionsClaimItem> item() {
        return this.item;
    }
    @Export(name="parameters", refs={LicensingSubscriptionSubscriptionsClaimParameters.class}, tree="[0]")
    private Output<LicensingSubscriptionSubscriptionsClaimParameters> parameters;

    public Output<LicensingSubscriptionSubscriptionsClaimParameters> parameters() {
        return this.parameters;
    }
    /**
     * validate query parameter. Check if the provided claim key is valid and can be claimed into the organization.
     * 
     */
    @Export(name="validate", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> validate;

    /**
     * @return validate query parameter. Check if the provided claim key is valid and can be claimed into the organization.
     * 
     */
    public Output<Optional<Boolean>> validate() {
        return Codegen.optional(this.validate);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public LicensingSubscriptionSubscriptionsClaim(java.lang.String name) {
        this(name, LicensingSubscriptionSubscriptionsClaimArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public LicensingSubscriptionSubscriptionsClaim(java.lang.String name, LicensingSubscriptionSubscriptionsClaimArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public LicensingSubscriptionSubscriptionsClaim(java.lang.String name, LicensingSubscriptionSubscriptionsClaimArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("meraki:administered/licensingSubscriptionSubscriptionsClaim:LicensingSubscriptionSubscriptionsClaim", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private LicensingSubscriptionSubscriptionsClaim(java.lang.String name, Output<java.lang.String> id, @Nullable LicensingSubscriptionSubscriptionsClaimState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("meraki:administered/licensingSubscriptionSubscriptionsClaim:LicensingSubscriptionSubscriptionsClaim", name, state, makeResourceOptions(options, id), false);
    }

    private static LicensingSubscriptionSubscriptionsClaimArgs makeArgs(LicensingSubscriptionSubscriptionsClaimArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? LicensingSubscriptionSubscriptionsClaimArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumi/pulumi-meraki")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static LicensingSubscriptionSubscriptionsClaim get(java.lang.String name, Output<java.lang.String> id, @Nullable LicensingSubscriptionSubscriptionsClaimState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new LicensingSubscriptionSubscriptionsClaim(name, id, state, options);
    }
}
