// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Networks.Inputs
{

    public sealed class ClientsSplashAuthorizationStatusSsidsStatus12Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// New authorization status for the SSID (true, false).
        /// </summary>
        [Input("isAuthorized")]
        public Input<bool>? IsAuthorized { get; set; }

        public ClientsSplashAuthorizationStatusSsidsStatus12Args()
        {
        }
        public static new ClientsSplashAuthorizationStatusSsidsStatus12Args Empty => new ClientsSplashAuthorizationStatusSsidsStatus12Args();
    }
}
