// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Networks.Inputs
{

    public sealed class SmDevicesModifyTagsParametersArgs : global::Pulumi.ResourceArgs
    {
        [Input("ids")]
        private InputList<string>? _ids;

        /// <summary>
        /// The ids of the devices to be modified.
        /// </summary>
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        [Input("scopes")]
        private InputList<string>? _scopes;

        /// <summary>
        /// The scope (one of all, none, withAny, withAll, withoutAny, or withoutAll) and a set of tags of the devices to be modified.
        /// </summary>
        public InputList<string> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<string>());
            set => _scopes = value;
        }

        [Input("serials")]
        private InputList<string>? _serials;

        /// <summary>
        /// The serials of the devices to be modified.
        /// </summary>
        public InputList<string> Serials
        {
            get => _serials ?? (_serials = new InputList<string>());
            set => _serials = value;
        }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tags to be added, deleted, or updated.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// One of add, delete, or update. Only devices that have been modified will be returned.
        /// </summary>
        [Input("updateAction")]
        public Input<string>? UpdateAction { get; set; }

        [Input("wifiMacs")]
        private InputList<string>? _wifiMacs;

        /// <summary>
        /// The wifiMacs of the devices to be modified.
        /// </summary>
        public InputList<string> WifiMacs
        {
            get => _wifiMacs ?? (_wifiMacs = new InputList<string>());
            set => _wifiMacs = value;
        }

        public SmDevicesModifyTagsParametersArgs()
        {
        }
        public static new SmDevicesModifyTagsParametersArgs Empty => new SmDevicesModifyTagsParametersArgs();
    }
}
