provider: meraki
major-version: 0
makeTemplate: bridged
team: ecosystem
providerDefaultBranch: main
esc:
    enabled: true
env:
    MERAKI_ORG_ID: ${{ secrets.MERAKI_ORG_ID }}
    MERAKI_DASHBOARD_API_KEY: ${{ secrets.MERAKI_DASHBOARD_API_KEY }}
pulumiConvert: 1
registryDocs: true
checkUpstreamUpgrade: false
integrationTestProvider: true
