// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * ## Example Usage
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import meraki:networks/firmwareUpgrades:FirmwareUpgrades example "network_id"
 * ```
 */
export class FirmwareUpgrades extends pulumi.CustomResource {
    /**
     * Get an existing FirmwareUpgrades resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FirmwareUpgradesState, opts?: pulumi.CustomResourceOptions): FirmwareUpgrades {
        return new FirmwareUpgrades(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'meraki:networks/firmwareUpgrades:FirmwareUpgrades';

    /**
     * Returns true if the given object is an instance of FirmwareUpgrades.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FirmwareUpgrades {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FirmwareUpgrades.__pulumiType;
    }

    /**
     * networkId path parameter. Network ID
     */
    public readonly networkId!: pulumi.Output<string>;
    /**
     * The network devices to be updated
     */
    public readonly products!: pulumi.Output<outputs.networks.FirmwareUpgradesProducts>;
    /**
     * The timezone for the network
     */
    public readonly timezone!: pulumi.Output<string>;
    /**
     * Upgrade window for devices in network
     */
    public readonly upgradeWindow!: pulumi.Output<outputs.networks.FirmwareUpgradesUpgradeWindow>;

    /**
     * Create a FirmwareUpgrades resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FirmwareUpgradesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FirmwareUpgradesArgs | FirmwareUpgradesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FirmwareUpgradesState | undefined;
            resourceInputs["networkId"] = state ? state.networkId : undefined;
            resourceInputs["products"] = state ? state.products : undefined;
            resourceInputs["timezone"] = state ? state.timezone : undefined;
            resourceInputs["upgradeWindow"] = state ? state.upgradeWindow : undefined;
        } else {
            const args = argsOrState as FirmwareUpgradesArgs | undefined;
            if ((!args || args.networkId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'networkId'");
            }
            resourceInputs["networkId"] = args ? args.networkId : undefined;
            resourceInputs["products"] = args ? args.products : undefined;
            resourceInputs["timezone"] = args ? args.timezone : undefined;
            resourceInputs["upgradeWindow"] = args ? args.upgradeWindow : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FirmwareUpgrades.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FirmwareUpgrades resources.
 */
export interface FirmwareUpgradesState {
    /**
     * networkId path parameter. Network ID
     */
    networkId?: pulumi.Input<string>;
    /**
     * The network devices to be updated
     */
    products?: pulumi.Input<inputs.networks.FirmwareUpgradesProducts>;
    /**
     * The timezone for the network
     */
    timezone?: pulumi.Input<string>;
    /**
     * Upgrade window for devices in network
     */
    upgradeWindow?: pulumi.Input<inputs.networks.FirmwareUpgradesUpgradeWindow>;
}

/**
 * The set of arguments for constructing a FirmwareUpgrades resource.
 */
export interface FirmwareUpgradesArgs {
    /**
     * networkId path parameter. Network ID
     */
    networkId: pulumi.Input<string>;
    /**
     * The network devices to be updated
     */
    products?: pulumi.Input<inputs.networks.FirmwareUpgradesProducts>;
    /**
     * The timezone for the network
     */
    timezone?: pulumi.Input<string>;
    /**
     * Upgrade window for devices in network
     */
    upgradeWindow?: pulumi.Input<inputs.networks.FirmwareUpgradesUpgradeWindow>;
}
