// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as meraki from "@pulumi/meraki";
 *
 * const example = meraki.networks.getApplianceFirewallInboundFirewallRules({
 *     networkId: "string",
 * });
 * export const merakiNetworksApplianceFirewallInboundFirewallRulesExample = example.then(example => example.item);
 * ```
 */
export function getApplianceFirewallInboundFirewallRules(args: GetApplianceFirewallInboundFirewallRulesArgs, opts?: pulumi.InvokeOptions): Promise<GetApplianceFirewallInboundFirewallRulesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("meraki:networks/getApplianceFirewallInboundFirewallRules:getApplianceFirewallInboundFirewallRules", {
        "networkId": args.networkId,
    }, opts);
}

/**
 * A collection of arguments for invoking getApplianceFirewallInboundFirewallRules.
 */
export interface GetApplianceFirewallInboundFirewallRulesArgs {
    /**
     * networkId path parameter. Network ID
     */
    networkId: string;
}

/**
 * A collection of values returned by getApplianceFirewallInboundFirewallRules.
 */
export interface GetApplianceFirewallInboundFirewallRulesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly item: outputs.networks.GetApplianceFirewallInboundFirewallRulesItem;
    /**
     * networkId path parameter. Network ID
     */
    readonly networkId: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as meraki from "@pulumi/meraki";
 *
 * const example = meraki.networks.getApplianceFirewallInboundFirewallRules({
 *     networkId: "string",
 * });
 * export const merakiNetworksApplianceFirewallInboundFirewallRulesExample = example.then(example => example.item);
 * ```
 */
export function getApplianceFirewallInboundFirewallRulesOutput(args: GetApplianceFirewallInboundFirewallRulesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetApplianceFirewallInboundFirewallRulesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("meraki:networks/getApplianceFirewallInboundFirewallRules:getApplianceFirewallInboundFirewallRules", {
        "networkId": args.networkId,
    }, opts);
}

/**
 * A collection of arguments for invoking getApplianceFirewallInboundFirewallRules.
 */
export interface GetApplianceFirewallInboundFirewallRulesOutputArgs {
    /**
     * networkId path parameter. Network ID
     */
    networkId: pulumi.Input<string>;
}
