// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as meraki from "@pulumi/meraki";
 *
 * const example = meraki.networks.getWirelessLatencyStats({
 *     apTag: "string",
 *     band: "string",
 *     fields: "string",
 *     networkId: "string",
 *     ssid: 1,
 *     t0: "string",
 *     t1: "string",
 *     timespan: 1,
 *     vlan: 1,
 * });
 * export const merakiNetworksWirelessLatencyStatsExample = example.then(example => example.item);
 * ```
 */
export function getWirelessLatencyStats(args: GetWirelessLatencyStatsArgs, opts?: pulumi.InvokeOptions): Promise<GetWirelessLatencyStatsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("meraki:networks/getWirelessLatencyStats:getWirelessLatencyStats", {
        "apTag": args.apTag,
        "band": args.band,
        "fields": args.fields,
        "networkId": args.networkId,
        "ssid": args.ssid,
        "t0": args.t0,
        "t1": args.t1,
        "timespan": args.timespan,
        "vlan": args.vlan,
    }, opts);
}

/**
 * A collection of arguments for invoking getWirelessLatencyStats.
 */
export interface GetWirelessLatencyStatsArgs {
    /**
     * apTag query parameter. Filter results by AP Tag
     */
    apTag?: string;
    /**
     * band query parameter. Filter results by band (either '2.4', '5' or '6'). Note that data prior to February 2020 will not have band information.
     */
    band?: string;
    /**
     * fields query parameter. Partial selection: If present, this call will return only the selected fields of ["rawDistribution", "avg"]. All fields will be returned by default. Selected fields must be entered as a comma separated string.
     */
    fields?: string;
    /**
     * networkId path parameter. Network ID
     */
    networkId: string;
    /**
     * ssid query parameter. Filter results by SSID
     */
    ssid?: number;
    /**
     * t0 query parameter. The beginning of the timespan for the data. The maximum lookback period is 180 days from today.
     */
    t0?: string;
    /**
     * t1 query parameter. The end of the timespan for the data. t1 can be a maximum of 7 days after t0.
     */
    t1?: string;
    /**
     * timespan query parameter. The timespan for which the information will be fetched. If specifying timespan, do not specify parameters t0 and t1. The value must be in seconds and be less than or equal to 7 days.
     */
    timespan?: number;
    /**
     * vlan query parameter. Filter results by VLAN
     */
    vlan?: number;
}

/**
 * A collection of values returned by getWirelessLatencyStats.
 */
export interface GetWirelessLatencyStatsResult {
    /**
     * apTag query parameter. Filter results by AP Tag
     */
    readonly apTag?: string;
    /**
     * band query parameter. Filter results by band (either '2.4', '5' or '6'). Note that data prior to February 2020 will not have band information.
     */
    readonly band?: string;
    /**
     * fields query parameter. Partial selection: If present, this call will return only the selected fields of ["rawDistribution", "avg"]. All fields will be returned by default. Selected fields must be entered as a comma separated string.
     */
    readonly fields?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly item: outputs.networks.GetWirelessLatencyStatsItem;
    /**
     * networkId path parameter. Network ID
     */
    readonly networkId: string;
    /**
     * ssid query parameter. Filter results by SSID
     */
    readonly ssid?: number;
    /**
     * t0 query parameter. The beginning of the timespan for the data. The maximum lookback period is 180 days from today.
     */
    readonly t0?: string;
    /**
     * t1 query parameter. The end of the timespan for the data. t1 can be a maximum of 7 days after t0.
     */
    readonly t1?: string;
    /**
     * timespan query parameter. The timespan for which the information will be fetched. If specifying timespan, do not specify parameters t0 and t1. The value must be in seconds and be less than or equal to 7 days.
     */
    readonly timespan?: number;
    /**
     * vlan query parameter. Filter results by VLAN
     */
    readonly vlan?: number;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as meraki from "@pulumi/meraki";
 *
 * const example = meraki.networks.getWirelessLatencyStats({
 *     apTag: "string",
 *     band: "string",
 *     fields: "string",
 *     networkId: "string",
 *     ssid: 1,
 *     t0: "string",
 *     t1: "string",
 *     timespan: 1,
 *     vlan: 1,
 * });
 * export const merakiNetworksWirelessLatencyStatsExample = example.then(example => example.item);
 * ```
 */
export function getWirelessLatencyStatsOutput(args: GetWirelessLatencyStatsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetWirelessLatencyStatsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("meraki:networks/getWirelessLatencyStats:getWirelessLatencyStats", {
        "apTag": args.apTag,
        "band": args.band,
        "fields": args.fields,
        "networkId": args.networkId,
        "ssid": args.ssid,
        "t0": args.t0,
        "t1": args.t1,
        "timespan": args.timespan,
        "vlan": args.vlan,
    }, opts);
}

/**
 * A collection of arguments for invoking getWirelessLatencyStats.
 */
export interface GetWirelessLatencyStatsOutputArgs {
    /**
     * apTag query parameter. Filter results by AP Tag
     */
    apTag?: pulumi.Input<string>;
    /**
     * band query parameter. Filter results by band (either '2.4', '5' or '6'). Note that data prior to February 2020 will not have band information.
     */
    band?: pulumi.Input<string>;
    /**
     * fields query parameter. Partial selection: If present, this call will return only the selected fields of ["rawDistribution", "avg"]. All fields will be returned by default. Selected fields must be entered as a comma separated string.
     */
    fields?: pulumi.Input<string>;
    /**
     * networkId path parameter. Network ID
     */
    networkId: pulumi.Input<string>;
    /**
     * ssid query parameter. Filter results by SSID
     */
    ssid?: pulumi.Input<number>;
    /**
     * t0 query parameter. The beginning of the timespan for the data. The maximum lookback period is 180 days from today.
     */
    t0?: pulumi.Input<string>;
    /**
     * t1 query parameter. The end of the timespan for the data. t1 can be a maximum of 7 days after t0.
     */
    t1?: pulumi.Input<string>;
    /**
     * timespan query parameter. The timespan for which the information will be fetched. If specifying timespan, do not specify parameters t0 and t1. The value must be in seconds and be less than or equal to 7 days.
     */
    timespan?: pulumi.Input<number>;
    /**
     * vlan query parameter. Filter results by VLAN
     */
    vlan?: pulumi.Input<number>;
}
