// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Networks.Outputs
{

    [OutputType]
    public sealed class GetSmUsersDeviceProfilesItemResult
    {
        /// <summary>
        /// The Meraki managed device Id.
        /// </summary>
        public readonly string DeviceId;
        /// <summary>
        /// The numerical Meraki Id of the profile.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A boolean indicating if the profile is encrypted.
        /// </summary>
        public readonly bool IsEncrypted;
        /// <summary>
        /// Whether or not the profile is managed by Meraki.
        /// </summary>
        public readonly bool IsManaged;
        /// <summary>
        /// The name of the profile.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// A string containing a JSON object with the profile data.
        /// </summary>
        public readonly string ProfileData;
        /// <summary>
        /// The identifier of the profile.
        /// </summary>
        public readonly string ProfileIdentifier;
        /// <summary>
        /// The verison of the profile.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetSmUsersDeviceProfilesItemResult(
            string deviceId,

            string id,

            bool isEncrypted,

            bool isManaged,

            string name,

            string profileData,

            string profileIdentifier,

            string version)
        {
            DeviceId = deviceId;
            Id = id;
            IsEncrypted = isEncrypted;
            IsManaged = isManaged;
            Name = name;
            ProfileData = profileData;
            ProfileIdentifier = profileIdentifier;
            Version = version;
        }
    }
}
