// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Networks.Outputs
{

    [OutputType]
    public sealed class GetSmDevicesDeviceCommandLogsItemResult
    {
        /// <summary>
        /// The type of command sent to the device.
        /// </summary>
        public readonly string Action;
        /// <summary>
        /// The Meraki dashboard user who initiated the command.
        /// </summary>
        public readonly string DashboardUser;
        /// <summary>
        /// A JSON string object containing command details.
        /// </summary>
        public readonly string Details;
        /// <summary>
        /// The name of the device to which the command is sent.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The time the command was sent to the device.
        /// </summary>
        public readonly string Ts;

        [OutputConstructor]
        private GetSmDevicesDeviceCommandLogsItemResult(
            string action,

            string dashboardUser,

            string details,

            string name,

            string ts)
        {
            Action = action;
            DashboardUser = dashboardUser;
            Details = details;
            Name = name;
            Ts = ts;
        }
    }
}
