// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Networks.Outputs
{

    [OutputType]
    public sealed class GetTopologyLinkLayerItemLinkEndDiscoveredResult
    {
        public readonly Outputs.GetTopologyLinkLayerItemLinkEndDiscoveredCdpResult Cdp;
        public readonly Outputs.GetTopologyLinkLayerItemLinkEndDiscoveredLldpResult Lldp;

        [OutputConstructor]
        private GetTopologyLinkLayerItemLinkEndDiscoveredResult(
            Outputs.GetTopologyLinkLayerItemLinkEndDiscoveredCdpResult cdp,

            Outputs.GetTopologyLinkLayerItemLinkEndDiscoveredLldpResult lldp)
        {
            Cdp = cdp;
            Lldp = lldp;
        }
    }
}
