// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Devices.Outputs
{

    [OutputType]
    public sealed class LiveToolsPingDeviceItem
    {
        /// <summary>
        /// Information for callback used to send back results
        /// </summary>
        public readonly Outputs.LiveToolsPingDeviceItemCallback? Callback;
        /// <summary>
        /// Id to check the status of your ping request.
        /// </summary>
        public readonly string? PingId;
        /// <summary>
        /// Ping request parameters
        /// </summary>
        public readonly Outputs.LiveToolsPingDeviceItemRequest? Request;
        /// <summary>
        /// Status of the ping request.
        /// </summary>
        public readonly string? Status;
        /// <summary>
        /// GET this url to check the status of your ping request.
        /// </summary>
        public readonly string? Url;

        [OutputConstructor]
        private LiveToolsPingDeviceItem(
            Outputs.LiveToolsPingDeviceItemCallback? callback,

            string? pingId,

            Outputs.LiveToolsPingDeviceItemRequest? request,

            string? status,

            string? url)
        {
            Callback = callback;
            PingId = pingId;
            Request = request;
            Status = status;
            Url = url;
        }
    }
}
