// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Organizations.Inputs
{

    public sealed class InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAuthenticationGroupGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Group Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAuthenticationGroupGetArgs()
        {
        }
        public static new InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAuthenticationGroupGetArgs Empty => new InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAuthenticationGroupGetArgs();
    }
}
