// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Organizations.Inputs
{

    public sealed class SmSentryPoliciesAssignmentsItemGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("items")]
        private InputList<Inputs.SmSentryPoliciesAssignmentsItemItemGetArgs>? _items;

        /// <summary>
        /// Sentry Group Policies for the Organization keyed by Network Id
        /// </summary>
        public InputList<Inputs.SmSentryPoliciesAssignmentsItemItemGetArgs> Items
        {
            get => _items ?? (_items = new InputList<Inputs.SmSentryPoliciesAssignmentsItemItemGetArgs>());
            set => _items = value;
        }

        public SmSentryPoliciesAssignmentsItemGetArgs()
        {
        }
        public static new SmSentryPoliciesAssignmentsItemGetArgs Empty => new SmSentryPoliciesAssignmentsItemGetArgs();
    }
}
