// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as meraki from "@pulumi/meraki";
 *
 * const example = meraki.organizations.getPolicyObjects({
 *     endingBefore: "string",
 *     organizationId: "string",
 *     perPage: 1,
 *     startingAfter: "string",
 * });
 * export const merakiOrganizationsPolicyObjectsExample = example.then(example => example.item);
 * ```
 */
export function getPolicyObjects(args?: GetPolicyObjectsArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyObjectsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("meraki:organizations/getPolicyObjects:getPolicyObjects", {
        "endingBefore": args.endingBefore,
        "organizationId": args.organizationId,
        "perPage": args.perPage,
        "policyObjectId": args.policyObjectId,
        "startingAfter": args.startingAfter,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicyObjects.
 */
export interface GetPolicyObjectsArgs {
    /**
     * endingBefore query parameter. A token used by the server to indicate the end of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.
     */
    endingBefore?: string;
    /**
     * organizationId path parameter. Organization ID
     */
    organizationId?: string;
    /**
     * perPage query parameter. The number of entries per page returned. Acceptable range is 10 5000. Default is 5000.
     */
    perPage?: number;
    /**
     * policyObjectId path parameter. Policy object ID
     */
    policyObjectId?: string;
    /**
     * startingAfter query parameter. A token used by the server to indicate the start of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.
     */
    startingAfter?: string;
}

/**
 * A collection of values returned by getPolicyObjects.
 */
export interface GetPolicyObjectsResult {
    /**
     * endingBefore query parameter. A token used by the server to indicate the end of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.
     */
    readonly endingBefore?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly item: outputs.organizations.GetPolicyObjectsItem;
    /**
     * organizationId path parameter. Organization ID
     */
    readonly organizationId?: string;
    /**
     * perPage query parameter. The number of entries per page returned. Acceptable range is 10 5000. Default is 5000.
     */
    readonly perPage?: number;
    /**
     * policyObjectId path parameter. Policy object ID
     */
    readonly policyObjectId?: string;
    /**
     * startingAfter query parameter. A token used by the server to indicate the start of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.
     */
    readonly startingAfter?: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as meraki from "@pulumi/meraki";
 *
 * const example = meraki.organizations.getPolicyObjects({
 *     endingBefore: "string",
 *     organizationId: "string",
 *     perPage: 1,
 *     startingAfter: "string",
 * });
 * export const merakiOrganizationsPolicyObjectsExample = example.then(example => example.item);
 * ```
 */
export function getPolicyObjectsOutput(args?: GetPolicyObjectsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPolicyObjectsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("meraki:organizations/getPolicyObjects:getPolicyObjects", {
        "endingBefore": args.endingBefore,
        "organizationId": args.organizationId,
        "perPage": args.perPage,
        "policyObjectId": args.policyObjectId,
        "startingAfter": args.startingAfter,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicyObjects.
 */
export interface GetPolicyObjectsOutputArgs {
    /**
     * endingBefore query parameter. A token used by the server to indicate the end of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.
     */
    endingBefore?: pulumi.Input<string>;
    /**
     * organizationId path parameter. Organization ID
     */
    organizationId?: pulumi.Input<string>;
    /**
     * perPage query parameter. The number of entries per page returned. Acceptable range is 10 5000. Default is 5000.
     */
    perPage?: pulumi.Input<number>;
    /**
     * policyObjectId path parameter. Policy object ID
     */
    policyObjectId?: pulumi.Input<string>;
    /**
     * startingAfter query parameter. A token used by the server to indicate the start of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.
     */
    startingAfter?: pulumi.Input<string>;
}
