// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.networks.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FirmwareUpgradesStagedEventsRollbacksItemProductsSwitchNextUpgradeToVersion {
    /**
     * @return Id of the Version being upgraded to
     * 
     */
    private @Nullable String id;
    /**
     * @return Firmware version short name
     * 
     */
    private @Nullable String shortName;

    private FirmwareUpgradesStagedEventsRollbacksItemProductsSwitchNextUpgradeToVersion() {}
    /**
     * @return Id of the Version being upgraded to
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return Firmware version short name
     * 
     */
    public Optional<String> shortName() {
        return Optional.ofNullable(this.shortName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FirmwareUpgradesStagedEventsRollbacksItemProductsSwitchNextUpgradeToVersion defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        private @Nullable String shortName;
        public Builder() {}
        public Builder(FirmwareUpgradesStagedEventsRollbacksItemProductsSwitchNextUpgradeToVersion defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.shortName = defaults.shortName;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder shortName(@Nullable String shortName) {

            this.shortName = shortName;
            return this;
        }
        public FirmwareUpgradesStagedEventsRollbacksItemProductsSwitchNextUpgradeToVersion build() {
            final var _resultValue = new FirmwareUpgradesStagedEventsRollbacksItemProductsSwitchNextUpgradeToVersion();
            _resultValue.id = id;
            _resultValue.shortName = shortName;
            return _resultValue;
        }
    }
}
