// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.networks.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.meraki.networks.outputs.GetFirmwareUpgradesItem;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetFirmwareUpgradesResult {
    private GetFirmwareUpgradesItem item;
    /**
     * @return networkId path parameter. Network ID
     * 
     */
    private String networkId;

    private GetFirmwareUpgradesResult() {}
    public GetFirmwareUpgradesItem item() {
        return this.item;
    }
    /**
     * @return networkId path parameter. Network ID
     * 
     */
    public String networkId() {
        return this.networkId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetFirmwareUpgradesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetFirmwareUpgradesItem item;
        private String networkId;
        public Builder() {}
        public Builder(GetFirmwareUpgradesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.item = defaults.item;
    	      this.networkId = defaults.networkId;
        }

        @CustomType.Setter
        public Builder item(GetFirmwareUpgradesItem item) {
            if (item == null) {
              throw new MissingRequiredPropertyException("GetFirmwareUpgradesResult", "item");
            }
            this.item = item;
            return this;
        }
        @CustomType.Setter
        public Builder networkId(String networkId) {
            if (networkId == null) {
              throw new MissingRequiredPropertyException("GetFirmwareUpgradesResult", "networkId");
            }
            this.networkId = networkId;
            return this;
        }
        public GetFirmwareUpgradesResult build() {
            final var _resultValue = new GetFirmwareUpgradesResult();
            _resultValue.item = item;
            _resultValue.networkId = networkId;
            return _resultValue;
        }
    }
}
