// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.networks.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class GetSwitchDhcpV4ServersSeenItemLastPacketIpDscp {
    /**
     * @return ECN number of the packet.
     * 
     */
    private Integer ecn;
    /**
     * @return DSCP tag number of the packet.
     * 
     */
    private Integer tag;

    private GetSwitchDhcpV4ServersSeenItemLastPacketIpDscp() {}
    /**
     * @return ECN number of the packet.
     * 
     */
    public Integer ecn() {
        return this.ecn;
    }
    /**
     * @return DSCP tag number of the packet.
     * 
     */
    public Integer tag() {
        return this.tag;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSwitchDhcpV4ServersSeenItemLastPacketIpDscp defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer ecn;
        private Integer tag;
        public Builder() {}
        public Builder(GetSwitchDhcpV4ServersSeenItemLastPacketIpDscp defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ecn = defaults.ecn;
    	      this.tag = defaults.tag;
        }

        @CustomType.Setter
        public Builder ecn(Integer ecn) {
            if (ecn == null) {
              throw new MissingRequiredPropertyException("GetSwitchDhcpV4ServersSeenItemLastPacketIpDscp", "ecn");
            }
            this.ecn = ecn;
            return this;
        }
        @CustomType.Setter
        public Builder tag(Integer tag) {
            if (tag == null) {
              throw new MissingRequiredPropertyException("GetSwitchDhcpV4ServersSeenItemLastPacketIpDscp", "tag");
            }
            this.tag = tag;
            return this;
        }
        public GetSwitchDhcpV4ServersSeenItemLastPacketIpDscp build() {
            final var _resultValue = new GetSwitchDhcpV4ServersSeenItemLastPacketIpDscp();
            _resultValue.ecn = ecn;
            _resultValue.tag = tag;
            return _resultValue;
        }
    }
}
