// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.networks.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class WirelessRfProfilesFiveGhzSettings {
    /**
     * @return Sets channel width (MHz) for 5Ghz band. Can be one of &#39;auto&#39;, &#39;20&#39;, &#39;40&#39; or &#39;80&#39;. Defaults to auto.
     * 
     */
    private @Nullable String channelWidth;
    /**
     * @return Sets max power (dBm) of 5Ghz band. Can be integer between 2 and 30. Defaults to 30.
     * 
     */
    private @Nullable Integer maxPower;
    /**
     * @return Sets min bitrate (Mbps) of 5Ghz band. Can be one of &#39;6&#39;, &#39;9&#39;, &#39;12&#39;, &#39;18&#39;, &#39;24&#39;, &#39;36&#39;, &#39;48&#39; or &#39;54&#39;. Defaults to 12.
     * 
     */
    private @Nullable Integer minBitrate;
    /**
     * @return Sets min power (dBm) of 5Ghz band. Can be integer between 2 and 30. Defaults to 8.
     * 
     */
    private @Nullable Integer minPower;
    /**
     * @return The RX-SOP level controls the sensitivity of the radio. It is strongly recommended to use RX-SOP only after consulting a wireless expert. RX-SOP can be configured in the range of -65 to -95 (dBm). A value of null will reset this to the default.
     * 
     */
    private @Nullable Integer rxsop;
    /**
     * @return Sets valid auto channels for 5Ghz band. Can be one of &#39;36&#39;, &#39;40&#39;, &#39;44&#39;, &#39;48&#39;, &#39;52&#39;, &#39;56&#39;, &#39;60&#39;, &#39;64&#39;, &#39;100&#39;, &#39;104&#39;, &#39;108&#39;, &#39;112&#39;, &#39;116&#39;, &#39;120&#39;, &#39;124&#39;, &#39;128&#39;, &#39;132&#39;, &#39;136&#39;, &#39;140&#39;, &#39;144&#39;, &#39;149&#39;, &#39;153&#39;, &#39;157&#39;, &#39;161&#39; or &#39;165&#39;.Defaults to [36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165].
     * 
     */
    private @Nullable List<Integer> validAutoChannels;

    private WirelessRfProfilesFiveGhzSettings() {}
    /**
     * @return Sets channel width (MHz) for 5Ghz band. Can be one of &#39;auto&#39;, &#39;20&#39;, &#39;40&#39; or &#39;80&#39;. Defaults to auto.
     * 
     */
    public Optional<String> channelWidth() {
        return Optional.ofNullable(this.channelWidth);
    }
    /**
     * @return Sets max power (dBm) of 5Ghz band. Can be integer between 2 and 30. Defaults to 30.
     * 
     */
    public Optional<Integer> maxPower() {
        return Optional.ofNullable(this.maxPower);
    }
    /**
     * @return Sets min bitrate (Mbps) of 5Ghz band. Can be one of &#39;6&#39;, &#39;9&#39;, &#39;12&#39;, &#39;18&#39;, &#39;24&#39;, &#39;36&#39;, &#39;48&#39; or &#39;54&#39;. Defaults to 12.
     * 
     */
    public Optional<Integer> minBitrate() {
        return Optional.ofNullable(this.minBitrate);
    }
    /**
     * @return Sets min power (dBm) of 5Ghz band. Can be integer between 2 and 30. Defaults to 8.
     * 
     */
    public Optional<Integer> minPower() {
        return Optional.ofNullable(this.minPower);
    }
    /**
     * @return The RX-SOP level controls the sensitivity of the radio. It is strongly recommended to use RX-SOP only after consulting a wireless expert. RX-SOP can be configured in the range of -65 to -95 (dBm). A value of null will reset this to the default.
     * 
     */
    public Optional<Integer> rxsop() {
        return Optional.ofNullable(this.rxsop);
    }
    /**
     * @return Sets valid auto channels for 5Ghz band. Can be one of &#39;36&#39;, &#39;40&#39;, &#39;44&#39;, &#39;48&#39;, &#39;52&#39;, &#39;56&#39;, &#39;60&#39;, &#39;64&#39;, &#39;100&#39;, &#39;104&#39;, &#39;108&#39;, &#39;112&#39;, &#39;116&#39;, &#39;120&#39;, &#39;124&#39;, &#39;128&#39;, &#39;132&#39;, &#39;136&#39;, &#39;140&#39;, &#39;144&#39;, &#39;149&#39;, &#39;153&#39;, &#39;157&#39;, &#39;161&#39; or &#39;165&#39;.Defaults to [36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165].
     * 
     */
    public List<Integer> validAutoChannels() {
        return this.validAutoChannels == null ? List.of() : this.validAutoChannels;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WirelessRfProfilesFiveGhzSettings defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String channelWidth;
        private @Nullable Integer maxPower;
        private @Nullable Integer minBitrate;
        private @Nullable Integer minPower;
        private @Nullable Integer rxsop;
        private @Nullable List<Integer> validAutoChannels;
        public Builder() {}
        public Builder(WirelessRfProfilesFiveGhzSettings defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.channelWidth = defaults.channelWidth;
    	      this.maxPower = defaults.maxPower;
    	      this.minBitrate = defaults.minBitrate;
    	      this.minPower = defaults.minPower;
    	      this.rxsop = defaults.rxsop;
    	      this.validAutoChannels = defaults.validAutoChannels;
        }

        @CustomType.Setter
        public Builder channelWidth(@Nullable String channelWidth) {

            this.channelWidth = channelWidth;
            return this;
        }
        @CustomType.Setter
        public Builder maxPower(@Nullable Integer maxPower) {

            this.maxPower = maxPower;
            return this;
        }
        @CustomType.Setter
        public Builder minBitrate(@Nullable Integer minBitrate) {

            this.minBitrate = minBitrate;
            return this;
        }
        @CustomType.Setter
        public Builder minPower(@Nullable Integer minPower) {

            this.minPower = minPower;
            return this;
        }
        @CustomType.Setter
        public Builder rxsop(@Nullable Integer rxsop) {

            this.rxsop = rxsop;
            return this;
        }
        @CustomType.Setter
        public Builder validAutoChannels(@Nullable List<Integer> validAutoChannels) {

            this.validAutoChannels = validAutoChannels;
            return this;
        }
        public Builder validAutoChannels(Integer... validAutoChannels) {
            return validAutoChannels(List.of(validAutoChannels));
        }
        public WirelessRfProfilesFiveGhzSettings build() {
            final var _resultValue = new WirelessRfProfilesFiveGhzSettings();
            _resultValue.channelWidth = channelWidth;
            _resultValue.maxPower = maxPower;
            _resultValue.minBitrate = minBitrate;
            _resultValue.minPower = minPower;
            _resultValue.rxsop = rxsop;
            _resultValue.validAutoChannels = validAutoChannels;
            return _resultValue;
        }
    }
}
