// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.devices.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CameraCustomAnalyticsParameterArgs extends com.pulumi.resources.ResourceArgs {

    public static final CameraCustomAnalyticsParameterArgs Empty = new CameraCustomAnalyticsParameterArgs();

    /**
     * Name of the parameter
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the parameter
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Value of the parameter
     * 
     */
    @Import(name="value")
    private @Nullable Output<Double> value;

    /**
     * @return Value of the parameter
     * 
     */
    public Optional<Output<Double>> value() {
        return Optional.ofNullable(this.value);
    }

    private CameraCustomAnalyticsParameterArgs() {}

    private CameraCustomAnalyticsParameterArgs(CameraCustomAnalyticsParameterArgs $) {
        this.name = $.name;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CameraCustomAnalyticsParameterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CameraCustomAnalyticsParameterArgs $;

        public Builder() {
            $ = new CameraCustomAnalyticsParameterArgs();
        }

        public Builder(CameraCustomAnalyticsParameterArgs defaults) {
            $ = new CameraCustomAnalyticsParameterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Name of the parameter
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the parameter
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param value Value of the parameter
         * 
         * @return builder
         * 
         */
        public Builder value(@Nullable Output<Double> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value Value of the parameter
         * 
         * @return builder
         * 
         */
        public Builder value(Double value) {
            return value(Output.of(value));
        }

        public CameraCustomAnalyticsParameterArgs build() {
            return $;
        }
    }

}
