// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.devices.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetSwitchRoutingInterfacesPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSwitchRoutingInterfacesPlainArgs Empty = new GetSwitchRoutingInterfacesPlainArgs();

    /**
     * interfaceId path parameter. Interface ID
     * 
     */
    @Import(name="interfaceId")
    private @Nullable String interfaceId;

    /**
     * @return interfaceId path parameter. Interface ID
     * 
     */
    public Optional<String> interfaceId() {
        return Optional.ofNullable(this.interfaceId);
    }

    /**
     * serial path parameter.
     * 
     */
    @Import(name="serial")
    private @Nullable String serial;

    /**
     * @return serial path parameter.
     * 
     */
    public Optional<String> serial() {
        return Optional.ofNullable(this.serial);
    }

    private GetSwitchRoutingInterfacesPlainArgs() {}

    private GetSwitchRoutingInterfacesPlainArgs(GetSwitchRoutingInterfacesPlainArgs $) {
        this.interfaceId = $.interfaceId;
        this.serial = $.serial;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSwitchRoutingInterfacesPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSwitchRoutingInterfacesPlainArgs $;

        public Builder() {
            $ = new GetSwitchRoutingInterfacesPlainArgs();
        }

        public Builder(GetSwitchRoutingInterfacesPlainArgs defaults) {
            $ = new GetSwitchRoutingInterfacesPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param interfaceId interfaceId path parameter. Interface ID
         * 
         * @return builder
         * 
         */
        public Builder interfaceId(@Nullable String interfaceId) {
            $.interfaceId = interfaceId;
            return this;
        }

        /**
         * @param serial serial path parameter.
         * 
         * @return builder
         * 
         */
        public Builder serial(@Nullable String serial) {
            $.serial = serial;
            return this;
        }

        public GetSwitchRoutingInterfacesPlainArgs build() {
            return $;
        }
    }

}
