// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Devices.Inputs
{

    public sealed class ApplianceUplinksSettingsInterfacesWan1Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable or disable the interface.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Configuration options for PPPoE.
        /// </summary>
        [Input("pppoe")]
        public Input<Inputs.ApplianceUplinksSettingsInterfacesWan1PppoeArgs>? Pppoe { get; set; }

        /// <summary>
        /// SVI settings by protocol.
        /// </summary>
        [Input("svis")]
        public Input<Inputs.ApplianceUplinksSettingsInterfacesWan1SvisArgs>? Svis { get; set; }

        /// <summary>
        /// VLAN tagging settings.
        /// </summary>
        [Input("vlanTagging")]
        public Input<Inputs.ApplianceUplinksSettingsInterfacesWan1VlanTaggingArgs>? VlanTagging { get; set; }

        public ApplianceUplinksSettingsInterfacesWan1Args()
        {
        }
        public static new ApplianceUplinksSettingsInterfacesWan1Args Empty => new ApplianceUplinksSettingsInterfacesWan1Args();
    }
}
