// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Devices.Inputs
{

    public sealed class ApplianceUplinksSettingsInterfacesWan2VlanTaggingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether VLAN tagging is enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The ID of the VLAN to use for VLAN tagging.
        /// </summary>
        [Input("vlanId")]
        public Input<int>? VlanId { get; set; }

        public ApplianceUplinksSettingsInterfacesWan2VlanTaggingGetArgs()
        {
        }
        public static new ApplianceUplinksSettingsInterfacesWan2VlanTaggingGetArgs Empty => new ApplianceUplinksSettingsInterfacesWan2VlanTaggingGetArgs();
    }
}
