// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.organizations.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.meraki.organizations.outputs.InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyIn;
import com.pulumi.meraki.organizations.outputs.InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyOut;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessList {
    /**
     * @return VTY in ACL
     * 
     */
    private @Nullable InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyIn vtyIn;
    /**
     * @return VTY out ACL
     * 
     */
    private @Nullable InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyOut vtyOut;

    private InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessList() {}
    /**
     * @return VTY in ACL
     * 
     */
    public Optional<InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyIn> vtyIn() {
        return Optional.ofNullable(this.vtyIn);
    }
    /**
     * @return VTY out ACL
     * 
     */
    public Optional<InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyOut> vtyOut() {
        return Optional.ofNullable(this.vtyOut);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessList defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyIn vtyIn;
        private @Nullable InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyOut vtyOut;
        public Builder() {}
        public Builder(InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessList defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.vtyIn = defaults.vtyIn;
    	      this.vtyOut = defaults.vtyOut;
        }

        @CustomType.Setter
        public Builder vtyIn(@Nullable InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyIn vtyIn) {

            this.vtyIn = vtyIn;
            return this;
        }
        @CustomType.Setter
        public Builder vtyOut(@Nullable InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessListVtyOut vtyOut) {

            this.vtyOut = vtyOut;
            return this;
        }
        public InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessList build() {
            final var _resultValue = new InventoryOnboardingCloudMonitoringPrepareParametersDeviceVtyAccessList();
            _resultValue.vtyIn = vtyIn;
            _resultValue.vtyOut = vtyOut;
            return _resultValue;
        }
    }
}
