// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Organizations.Outputs
{

    [OutputType]
    public sealed class GetLicensesOverviewItemSystemsManagerCountsResult
    {
        /// <summary>
        /// The number of Systems Manager seats in use
        /// </summary>
        public readonly int ActiveSeats;
        /// <summary>
        /// The total number of enrolled Systems Manager devices
        /// </summary>
        public readonly int OrgwideEnrolledDevices;
        /// <summary>
        /// The total number of Systems Manager seats
        /// </summary>
        public readonly int TotalSeats;
        /// <summary>
        /// The number of unused Systems Manager seats
        /// </summary>
        public readonly int UnassignedSeats;

        [OutputConstructor]
        private GetLicensesOverviewItemSystemsManagerCountsResult(
            int activeSeats,

            int orgwideEnrolledDevices,

            int totalSeats,

            int unassignedSeats)
        {
            ActiveSeats = activeSeats;
            OrgwideEnrolledDevices = orgwideEnrolledDevices;
            TotalSeats = totalSeats;
            UnassignedSeats = unassignedSeats;
        }
    }
}
