// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Organizations.Outputs
{

    [OutputType]
    public sealed class GetUplinksStatusesItemUplinkSignalStatResult
    {
        /// <summary>
        /// Reference Signal Received Power
        /// </summary>
        public readonly string Rsrp;
        /// <summary>
        /// Reference Signal Received Quality
        /// </summary>
        public readonly string Rsrq;

        [OutputConstructor]
        private GetUplinksStatusesItemUplinkSignalStatResult(
            string rsrp,

            string rsrq)
        {
            Rsrp = rsrp;
            Rsrq = rsrq;
        }
    }
}
