// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package networks

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-meraki/sdk/go/meraki/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ~>Warning: This resource does not represent a real-world entity in Meraki Dashboard, therefore changing or deleting this resource on its own has no immediate effect. Instead, it is a task part of a Meraki Dashboard workflow. It is executed in Meraki without any additional verification. It does not check if it was executed before or if a similar configuration or action
// already existed previously.
type ApplianceTrafficShapingCustomPerformanceClasses struct {
	pulumi.CustomResourceState

	// networkId path parameter. Network ID
	NetworkId  pulumi.StringOutput                                             `pulumi:"networkId"`
	Parameters ApplianceTrafficShapingCustomPerformanceClassesParametersOutput `pulumi:"parameters"`
}

// NewApplianceTrafficShapingCustomPerformanceClasses registers a new resource with the given unique name, arguments, and options.
func NewApplianceTrafficShapingCustomPerformanceClasses(ctx *pulumi.Context,
	name string, args *ApplianceTrafficShapingCustomPerformanceClassesArgs, opts ...pulumi.ResourceOption) (*ApplianceTrafficShapingCustomPerformanceClasses, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NetworkId == nil {
		return nil, errors.New("invalid value for required argument 'NetworkId'")
	}
	if args.Parameters == nil {
		return nil, errors.New("invalid value for required argument 'Parameters'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ApplianceTrafficShapingCustomPerformanceClasses
	err := ctx.RegisterResource("meraki:networks/applianceTrafficShapingCustomPerformanceClasses:ApplianceTrafficShapingCustomPerformanceClasses", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApplianceTrafficShapingCustomPerformanceClasses gets an existing ApplianceTrafficShapingCustomPerformanceClasses resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApplianceTrafficShapingCustomPerformanceClasses(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApplianceTrafficShapingCustomPerformanceClassesState, opts ...pulumi.ResourceOption) (*ApplianceTrafficShapingCustomPerformanceClasses, error) {
	var resource ApplianceTrafficShapingCustomPerformanceClasses
	err := ctx.ReadResource("meraki:networks/applianceTrafficShapingCustomPerformanceClasses:ApplianceTrafficShapingCustomPerformanceClasses", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApplianceTrafficShapingCustomPerformanceClasses resources.
type applianceTrafficShapingCustomPerformanceClassesState struct {
	// networkId path parameter. Network ID
	NetworkId  *string                                                    `pulumi:"networkId"`
	Parameters *ApplianceTrafficShapingCustomPerformanceClassesParameters `pulumi:"parameters"`
}

type ApplianceTrafficShapingCustomPerformanceClassesState struct {
	// networkId path parameter. Network ID
	NetworkId  pulumi.StringPtrInput
	Parameters ApplianceTrafficShapingCustomPerformanceClassesParametersPtrInput
}

func (ApplianceTrafficShapingCustomPerformanceClassesState) ElementType() reflect.Type {
	return reflect.TypeOf((*applianceTrafficShapingCustomPerformanceClassesState)(nil)).Elem()
}

type applianceTrafficShapingCustomPerformanceClassesArgs struct {
	// networkId path parameter. Network ID
	NetworkId  string                                                    `pulumi:"networkId"`
	Parameters ApplianceTrafficShapingCustomPerformanceClassesParameters `pulumi:"parameters"`
}

// The set of arguments for constructing a ApplianceTrafficShapingCustomPerformanceClasses resource.
type ApplianceTrafficShapingCustomPerformanceClassesArgs struct {
	// networkId path parameter. Network ID
	NetworkId  pulumi.StringInput
	Parameters ApplianceTrafficShapingCustomPerformanceClassesParametersInput
}

func (ApplianceTrafficShapingCustomPerformanceClassesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*applianceTrafficShapingCustomPerformanceClassesArgs)(nil)).Elem()
}

type ApplianceTrafficShapingCustomPerformanceClassesInput interface {
	pulumi.Input

	ToApplianceTrafficShapingCustomPerformanceClassesOutput() ApplianceTrafficShapingCustomPerformanceClassesOutput
	ToApplianceTrafficShapingCustomPerformanceClassesOutputWithContext(ctx context.Context) ApplianceTrafficShapingCustomPerformanceClassesOutput
}

func (*ApplianceTrafficShapingCustomPerformanceClasses) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplianceTrafficShapingCustomPerformanceClasses)(nil)).Elem()
}

func (i *ApplianceTrafficShapingCustomPerformanceClasses) ToApplianceTrafficShapingCustomPerformanceClassesOutput() ApplianceTrafficShapingCustomPerformanceClassesOutput {
	return i.ToApplianceTrafficShapingCustomPerformanceClassesOutputWithContext(context.Background())
}

func (i *ApplianceTrafficShapingCustomPerformanceClasses) ToApplianceTrafficShapingCustomPerformanceClassesOutputWithContext(ctx context.Context) ApplianceTrafficShapingCustomPerformanceClassesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplianceTrafficShapingCustomPerformanceClassesOutput)
}

// ApplianceTrafficShapingCustomPerformanceClassesArrayInput is an input type that accepts ApplianceTrafficShapingCustomPerformanceClassesArray and ApplianceTrafficShapingCustomPerformanceClassesArrayOutput values.
// You can construct a concrete instance of `ApplianceTrafficShapingCustomPerformanceClassesArrayInput` via:
//
//	ApplianceTrafficShapingCustomPerformanceClassesArray{ ApplianceTrafficShapingCustomPerformanceClassesArgs{...} }
type ApplianceTrafficShapingCustomPerformanceClassesArrayInput interface {
	pulumi.Input

	ToApplianceTrafficShapingCustomPerformanceClassesArrayOutput() ApplianceTrafficShapingCustomPerformanceClassesArrayOutput
	ToApplianceTrafficShapingCustomPerformanceClassesArrayOutputWithContext(context.Context) ApplianceTrafficShapingCustomPerformanceClassesArrayOutput
}

type ApplianceTrafficShapingCustomPerformanceClassesArray []ApplianceTrafficShapingCustomPerformanceClassesInput

func (ApplianceTrafficShapingCustomPerformanceClassesArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplianceTrafficShapingCustomPerformanceClasses)(nil)).Elem()
}

func (i ApplianceTrafficShapingCustomPerformanceClassesArray) ToApplianceTrafficShapingCustomPerformanceClassesArrayOutput() ApplianceTrafficShapingCustomPerformanceClassesArrayOutput {
	return i.ToApplianceTrafficShapingCustomPerformanceClassesArrayOutputWithContext(context.Background())
}

func (i ApplianceTrafficShapingCustomPerformanceClassesArray) ToApplianceTrafficShapingCustomPerformanceClassesArrayOutputWithContext(ctx context.Context) ApplianceTrafficShapingCustomPerformanceClassesArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplianceTrafficShapingCustomPerformanceClassesArrayOutput)
}

// ApplianceTrafficShapingCustomPerformanceClassesMapInput is an input type that accepts ApplianceTrafficShapingCustomPerformanceClassesMap and ApplianceTrafficShapingCustomPerformanceClassesMapOutput values.
// You can construct a concrete instance of `ApplianceTrafficShapingCustomPerformanceClassesMapInput` via:
//
//	ApplianceTrafficShapingCustomPerformanceClassesMap{ "key": ApplianceTrafficShapingCustomPerformanceClassesArgs{...} }
type ApplianceTrafficShapingCustomPerformanceClassesMapInput interface {
	pulumi.Input

	ToApplianceTrafficShapingCustomPerformanceClassesMapOutput() ApplianceTrafficShapingCustomPerformanceClassesMapOutput
	ToApplianceTrafficShapingCustomPerformanceClassesMapOutputWithContext(context.Context) ApplianceTrafficShapingCustomPerformanceClassesMapOutput
}

type ApplianceTrafficShapingCustomPerformanceClassesMap map[string]ApplianceTrafficShapingCustomPerformanceClassesInput

func (ApplianceTrafficShapingCustomPerformanceClassesMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplianceTrafficShapingCustomPerformanceClasses)(nil)).Elem()
}

func (i ApplianceTrafficShapingCustomPerformanceClassesMap) ToApplianceTrafficShapingCustomPerformanceClassesMapOutput() ApplianceTrafficShapingCustomPerformanceClassesMapOutput {
	return i.ToApplianceTrafficShapingCustomPerformanceClassesMapOutputWithContext(context.Background())
}

func (i ApplianceTrafficShapingCustomPerformanceClassesMap) ToApplianceTrafficShapingCustomPerformanceClassesMapOutputWithContext(ctx context.Context) ApplianceTrafficShapingCustomPerformanceClassesMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplianceTrafficShapingCustomPerformanceClassesMapOutput)
}

type ApplianceTrafficShapingCustomPerformanceClassesOutput struct{ *pulumi.OutputState }

func (ApplianceTrafficShapingCustomPerformanceClassesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplianceTrafficShapingCustomPerformanceClasses)(nil)).Elem()
}

func (o ApplianceTrafficShapingCustomPerformanceClassesOutput) ToApplianceTrafficShapingCustomPerformanceClassesOutput() ApplianceTrafficShapingCustomPerformanceClassesOutput {
	return o
}

func (o ApplianceTrafficShapingCustomPerformanceClassesOutput) ToApplianceTrafficShapingCustomPerformanceClassesOutputWithContext(ctx context.Context) ApplianceTrafficShapingCustomPerformanceClassesOutput {
	return o
}

// networkId path parameter. Network ID
func (o ApplianceTrafficShapingCustomPerformanceClassesOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplianceTrafficShapingCustomPerformanceClasses) pulumi.StringOutput { return v.NetworkId }).(pulumi.StringOutput)
}

func (o ApplianceTrafficShapingCustomPerformanceClassesOutput) Parameters() ApplianceTrafficShapingCustomPerformanceClassesParametersOutput {
	return o.ApplyT(func(v *ApplianceTrafficShapingCustomPerformanceClasses) ApplianceTrafficShapingCustomPerformanceClassesParametersOutput {
		return v.Parameters
	}).(ApplianceTrafficShapingCustomPerformanceClassesParametersOutput)
}

type ApplianceTrafficShapingCustomPerformanceClassesArrayOutput struct{ *pulumi.OutputState }

func (ApplianceTrafficShapingCustomPerformanceClassesArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplianceTrafficShapingCustomPerformanceClasses)(nil)).Elem()
}

func (o ApplianceTrafficShapingCustomPerformanceClassesArrayOutput) ToApplianceTrafficShapingCustomPerformanceClassesArrayOutput() ApplianceTrafficShapingCustomPerformanceClassesArrayOutput {
	return o
}

func (o ApplianceTrafficShapingCustomPerformanceClassesArrayOutput) ToApplianceTrafficShapingCustomPerformanceClassesArrayOutputWithContext(ctx context.Context) ApplianceTrafficShapingCustomPerformanceClassesArrayOutput {
	return o
}

func (o ApplianceTrafficShapingCustomPerformanceClassesArrayOutput) Index(i pulumi.IntInput) ApplianceTrafficShapingCustomPerformanceClassesOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ApplianceTrafficShapingCustomPerformanceClasses {
		return vs[0].([]*ApplianceTrafficShapingCustomPerformanceClasses)[vs[1].(int)]
	}).(ApplianceTrafficShapingCustomPerformanceClassesOutput)
}

type ApplianceTrafficShapingCustomPerformanceClassesMapOutput struct{ *pulumi.OutputState }

func (ApplianceTrafficShapingCustomPerformanceClassesMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplianceTrafficShapingCustomPerformanceClasses)(nil)).Elem()
}

func (o ApplianceTrafficShapingCustomPerformanceClassesMapOutput) ToApplianceTrafficShapingCustomPerformanceClassesMapOutput() ApplianceTrafficShapingCustomPerformanceClassesMapOutput {
	return o
}

func (o ApplianceTrafficShapingCustomPerformanceClassesMapOutput) ToApplianceTrafficShapingCustomPerformanceClassesMapOutputWithContext(ctx context.Context) ApplianceTrafficShapingCustomPerformanceClassesMapOutput {
	return o
}

func (o ApplianceTrafficShapingCustomPerformanceClassesMapOutput) MapIndex(k pulumi.StringInput) ApplianceTrafficShapingCustomPerformanceClassesOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ApplianceTrafficShapingCustomPerformanceClasses {
		return vs[0].(map[string]*ApplianceTrafficShapingCustomPerformanceClasses)[vs[1].(string)]
	}).(ApplianceTrafficShapingCustomPerformanceClassesOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApplianceTrafficShapingCustomPerformanceClassesInput)(nil)).Elem(), &ApplianceTrafficShapingCustomPerformanceClasses{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplianceTrafficShapingCustomPerformanceClassesArrayInput)(nil)).Elem(), ApplianceTrafficShapingCustomPerformanceClassesArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplianceTrafficShapingCustomPerformanceClassesMapInput)(nil)).Elem(), ApplianceTrafficShapingCustomPerformanceClassesMap{})
	pulumi.RegisterOutputType(ApplianceTrafficShapingCustomPerformanceClassesOutput{})
	pulumi.RegisterOutputType(ApplianceTrafficShapingCustomPerformanceClassesArrayOutput{})
	pulumi.RegisterOutputType(ApplianceTrafficShapingCustomPerformanceClassesMapOutput{})
}
