// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.organizations.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetApplianceUplinksStatusesOverviewPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetApplianceUplinksStatusesOverviewPlainArgs Empty = new GetApplianceUplinksStatusesOverviewPlainArgs();

    /**
     * organizationId path parameter. Organization ID
     * 
     */
    @Import(name="organizationId", required=true)
    private String organizationId;

    /**
     * @return organizationId path parameter. Organization ID
     * 
     */
    public String organizationId() {
        return this.organizationId;
    }

    private GetApplianceUplinksStatusesOverviewPlainArgs() {}

    private GetApplianceUplinksStatusesOverviewPlainArgs(GetApplianceUplinksStatusesOverviewPlainArgs $) {
        this.organizationId = $.organizationId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetApplianceUplinksStatusesOverviewPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetApplianceUplinksStatusesOverviewPlainArgs $;

        public Builder() {
            $ = new GetApplianceUplinksStatusesOverviewPlainArgs();
        }

        public Builder(GetApplianceUplinksStatusesOverviewPlainArgs defaults) {
            $ = new GetApplianceUplinksStatusesOverviewPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param organizationId organizationId path parameter. Organization ID
         * 
         * @return builder
         * 
         */
        public Builder organizationId(String organizationId) {
            $.organizationId = organizationId;
            return this;
        }

        public GetApplianceUplinksStatusesOverviewPlainArgs build() {
            if ($.organizationId == null) {
                throw new MissingRequiredPropertyException("GetApplianceUplinksStatusesOverviewPlainArgs", "organizationId");
            }
            return $;
        }
    }

}
