// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.networks;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.meraki.Utilities;
import com.pulumi.meraki.networks.SmDevicesWipeArgs;
import com.pulumi.meraki.networks.inputs.SmDevicesWipeState;
import com.pulumi.meraki.networks.outputs.SmDevicesWipeItem;
import com.pulumi.meraki.networks.outputs.SmDevicesWipeParameters;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * ~&gt;Warning: This resource does not represent a real-world entity in Meraki Dashboard, therefore changing or deleting this resource on its own has no immediate effect. Instead, it is a task part of a Meraki Dashboard workflow. It is executed in Meraki without any additional verification. It does not check if it was executed before or if a similar configuration or action
 * already existed previously.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.meraki.networks.SmDevicesWipe;
 * import com.pulumi.meraki.networks.SmDevicesWipeArgs;
 * import com.pulumi.meraki.networks.inputs.SmDevicesWipeParametersArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new SmDevicesWipe(&#34;example&#34;, SmDevicesWipeArgs.builder()        
 *             .networkId(&#34;string&#34;)
 *             .parameters(SmDevicesWipeParametersArgs.builder()
 *                 .id(&#34;1284392014819&#34;)
 *                 .pin(123456)
 *                 .serial(&#34;XY0XX0Y0X0&#34;)
 *                 .wifi_mac(&#34;00:11:22:33:44:55&#34;)
 *                 .build())
 *             .build());
 * 
 *         ctx.export(&#34;merakiNetworksSmDevicesWipeExample&#34;, example);
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="meraki:networks/smDevicesWipe:SmDevicesWipe")
public class SmDevicesWipe extends com.pulumi.resources.CustomResource {
    @Export(name="item", refs={SmDevicesWipeItem.class}, tree="[0]")
    private Output<SmDevicesWipeItem> item;

    public Output<SmDevicesWipeItem> item() {
        return this.item;
    }
    /**
     * networkId path parameter. Network ID
     * 
     */
    @Export(name="networkId", refs={String.class}, tree="[0]")
    private Output<String> networkId;

    /**
     * @return networkId path parameter. Network ID
     * 
     */
    public Output<String> networkId() {
        return this.networkId;
    }
    @Export(name="parameters", refs={SmDevicesWipeParameters.class}, tree="[0]")
    private Output<SmDevicesWipeParameters> parameters;

    public Output<SmDevicesWipeParameters> parameters() {
        return this.parameters;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SmDevicesWipe(String name) {
        this(name, SmDevicesWipeArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SmDevicesWipe(String name, SmDevicesWipeArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SmDevicesWipe(String name, SmDevicesWipeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("meraki:networks/smDevicesWipe:SmDevicesWipe", name, args == null ? SmDevicesWipeArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private SmDevicesWipe(String name, Output<String> id, @Nullable SmDevicesWipeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("meraki:networks/smDevicesWipe:SmDevicesWipe", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SmDevicesWipe get(String name, Output<String> id, @Nullable SmDevicesWipeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SmDevicesWipe(name, id, state, options);
    }
}
