// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.meraki.organizations;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.meraki.Utilities;
import com.pulumi.meraki.organizations.AdaptivePolicySettingsArgs;
import com.pulumi.meraki.organizations.inputs.AdaptivePolicySettingsState;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.meraki.organizations.AdaptivePolicySettings;
 * import com.pulumi.meraki.organizations.AdaptivePolicySettingsArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new AdaptivePolicySettings("example", AdaptivePolicySettingsArgs.builder()
 *             .enabledNetworks(            
 *                 "L_11111111",
 *                 "L_22222222",
 *                 "N_33333333",
 *                 "L_44444444")
 *             .organizationId("string")
 *             .build());
 * 
 *         ctx.export("merakiOrganizationsAdaptivePolicySettingsExample", example);
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import meraki:organizations/adaptivePolicySettings:AdaptivePolicySettings example &#34;organization_id&#34;
 * ```
 * 
 */
@ResourceType(type="meraki:organizations/adaptivePolicySettings:AdaptivePolicySettings")
public class AdaptivePolicySettings extends com.pulumi.resources.CustomResource {
    /**
     * List of network IDs with adaptive policy enabled
     * 
     */
    @Export(name="enabledNetworks", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> enabledNetworks;

    /**
     * @return List of network IDs with adaptive policy enabled
     * 
     */
    public Output<List<String>> enabledNetworks() {
        return this.enabledNetworks;
    }
    /**
     * organizationId path parameter. Organization ID
     * 
     */
    @Export(name="organizationId", refs={String.class}, tree="[0]")
    private Output<String> organizationId;

    /**
     * @return organizationId path parameter. Organization ID
     * 
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AdaptivePolicySettings(java.lang.String name) {
        this(name, AdaptivePolicySettingsArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AdaptivePolicySettings(java.lang.String name, AdaptivePolicySettingsArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AdaptivePolicySettings(java.lang.String name, AdaptivePolicySettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("meraki:organizations/adaptivePolicySettings:AdaptivePolicySettings", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private AdaptivePolicySettings(java.lang.String name, Output<java.lang.String> id, @Nullable AdaptivePolicySettingsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("meraki:organizations/adaptivePolicySettings:AdaptivePolicySettings", name, state, makeResourceOptions(options, id), false);
    }

    private static AdaptivePolicySettingsArgs makeArgs(AdaptivePolicySettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AdaptivePolicySettingsArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumi/pulumi-meraki")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AdaptivePolicySettings get(java.lang.String name, Output<java.lang.String> id, @Nullable AdaptivePolicySettingsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AdaptivePolicySettings(name, id, state, options);
    }
}
