// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Networks
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Meraki = Pulumi.Meraki;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Meraki.Networks.ClientsPolicy("example", new()
    ///     {
    ///         ClientId = "string",
    ///         DevicePolicy = "Group policy",
    ///         GroupPolicyId = "101",
    ///         NetworkId = "string",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["merakiNetworksClientsPolicyExample"] = example,
    ///     };
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import meraki:networks/clientsPolicy:ClientsPolicy example "client_id,network_id"
    /// ```
    /// </summary>
    [MerakiResourceType("meraki:networks/clientsPolicy:ClientsPolicy")]
    public partial class ClientsPolicy : global::Pulumi.CustomResource
    {
        /// <summary>
        /// clientId path parameter. Client ID
        /// </summary>
        [Output("clientId")]
        public Output<string> ClientId { get; private set; } = null!;

        /// <summary>
        /// The name of the client's policy
        /// </summary>
        [Output("devicePolicy")]
        public Output<string> DevicePolicy { get; private set; } = null!;

        /// <summary>
        /// The group policy identifier of the client
        /// </summary>
        [Output("groupPolicyId")]
        public Output<string> GroupPolicyId { get; private set; } = null!;

        /// <summary>
        /// The MAC address of the client
        /// </summary>
        [Output("mac")]
        public Output<string> Mac { get; private set; } = null!;

        /// <summary>
        /// networkId path parameter. Network ID
        /// </summary>
        [Output("networkId")]
        public Output<string> NetworkId { get; private set; } = null!;


        /// <summary>
        /// Create a ClientsPolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ClientsPolicy(string name, ClientsPolicyArgs args, CustomResourceOptions? options = null)
            : base("meraki:networks/clientsPolicy:ClientsPolicy", name, args ?? new ClientsPolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ClientsPolicy(string name, Input<string> id, ClientsPolicyState? state = null, CustomResourceOptions? options = null)
            : base("meraki:networks/clientsPolicy:ClientsPolicy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi/pulumi-meraki",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ClientsPolicy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ClientsPolicy Get(string name, Input<string> id, ClientsPolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new ClientsPolicy(name, id, state, options);
        }
    }

    public sealed class ClientsPolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// clientId path parameter. Client ID
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// The name of the client's policy
        /// </summary>
        [Input("devicePolicy")]
        public Input<string>? DevicePolicy { get; set; }

        /// <summary>
        /// The group policy identifier of the client
        /// </summary>
        [Input("groupPolicyId")]
        public Input<string>? GroupPolicyId { get; set; }

        /// <summary>
        /// networkId path parameter. Network ID
        /// </summary>
        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        public ClientsPolicyArgs()
        {
        }
        public static new ClientsPolicyArgs Empty => new ClientsPolicyArgs();
    }

    public sealed class ClientsPolicyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// clientId path parameter. Client ID
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// The name of the client's policy
        /// </summary>
        [Input("devicePolicy")]
        public Input<string>? DevicePolicy { get; set; }

        /// <summary>
        /// The group policy identifier of the client
        /// </summary>
        [Input("groupPolicyId")]
        public Input<string>? GroupPolicyId { get; set; }

        /// <summary>
        /// The MAC address of the client
        /// </summary>
        [Input("mac")]
        public Input<string>? Mac { get; set; }

        /// <summary>
        /// networkId path parameter. Network ID
        /// </summary>
        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        public ClientsPolicyState()
        {
        }
        public static new ClientsPolicyState Empty => new ClientsPolicyState();
    }
}
