// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Meraki.Networks
{
    public static class GetSwitchAccessPolicies
    {
        /// <summary>
        /// ## Example Usage
        /// </summary>
        public static Task<GetSwitchAccessPoliciesResult> InvokeAsync(GetSwitchAccessPoliciesArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSwitchAccessPoliciesResult>("meraki:networks/getSwitchAccessPolicies:getSwitchAccessPolicies", args ?? new GetSwitchAccessPoliciesArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// </summary>
        public static Output<GetSwitchAccessPoliciesResult> Invoke(GetSwitchAccessPoliciesInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSwitchAccessPoliciesResult>("meraki:networks/getSwitchAccessPolicies:getSwitchAccessPolicies", args ?? new GetSwitchAccessPoliciesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSwitchAccessPoliciesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// accessPolicyNumber path parameter. Access policy number
        /// </summary>
        [Input("accessPolicyNumber")]
        public string? AccessPolicyNumber { get; set; }

        /// <summary>
        /// networkId path parameter. Network ID
        /// </summary>
        [Input("networkId")]
        public string? NetworkId { get; set; }

        public GetSwitchAccessPoliciesArgs()
        {
        }
        public static new GetSwitchAccessPoliciesArgs Empty => new GetSwitchAccessPoliciesArgs();
    }

    public sealed class GetSwitchAccessPoliciesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// accessPolicyNumber path parameter. Access policy number
        /// </summary>
        [Input("accessPolicyNumber")]
        public Input<string>? AccessPolicyNumber { get; set; }

        /// <summary>
        /// networkId path parameter. Network ID
        /// </summary>
        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        public GetSwitchAccessPoliciesInvokeArgs()
        {
        }
        public static new GetSwitchAccessPoliciesInvokeArgs Empty => new GetSwitchAccessPoliciesInvokeArgs();
    }


    [OutputType]
    public sealed class GetSwitchAccessPoliciesResult
    {
        /// <summary>
        /// accessPolicyNumber path parameter. Access policy number
        /// </summary>
        public readonly string? AccessPolicyNumber;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly Outputs.GetSwitchAccessPoliciesItemResult Item;
        /// <summary>
        /// Array of ResponseSwitchGetNetworkSwitchAccessPolicies
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSwitchAccessPoliciesItemResult> Items;
        /// <summary>
        /// networkId path parameter. Network ID
        /// </summary>
        public readonly string? NetworkId;

        [OutputConstructor]
        private GetSwitchAccessPoliciesResult(
            string? accessPolicyNumber,

            string id,

            Outputs.GetSwitchAccessPoliciesItemResult item,

            ImmutableArray<Outputs.GetSwitchAccessPoliciesItemResult> items,

            string? networkId)
        {
            AccessPolicyNumber = accessPolicyNumber;
            Id = id;
            Item = item;
            Items = items;
            NetworkId = networkId;
        }
    }
}
